<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>video_image_converter_py</name>
  <version>0.1.0</version>
  <description>Generic ROS 2 video file to Image topic converter.</description>
  <maintainer email="info@dotxautomation.com">dotX Automation s.r.l.</maintainer>
  <license>Apache-2.0</license>

  <depend>dua_node_py</depend>
  <depend>dua_qos_py</depend>
  <depend>params_manager_py</depend>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <exec_depend>python3-opencv</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
